### ISSUE TITLE
wpGUI

### ISSUE THREAD

**Issue by wpshadow** [wpshadow/towerDefence#1]
## wpGUI Main Task für v0.1

- [ ] [wpGUI Color Mangement](https://github.com/wpshadow/towerDefence/issues/3)
- [ ] [wpGUI Color Scheme](https://github.com/wpshadow/towerDefence/issues/10)
- [x] Rounded Rects
http://www.glbasic.com/forum/index.php?topic=1877.0
- [ ] [wpGUI Settings](https://github.com/wpshadow/towerDefence/issues/5)
- [ ] [wpGUI Callback](https://github.com/wpshadow/towerDefence/issues/8)
- [x] [wpGUI Button](https://github.com/wpshadow/towerDefence/issues/2)
- [x] [wpGUI Radio Button](https://github.com/wpshadow/towerDefence/issues/4)
- [x] [wpGUI Label](https://github.com/wpshadow/towerDefence/issues/6)
- [ ] [wpGUI Schalter](https://github.com/wpshadow/towerDefence/issues/7)
- [ ] [wpGUI Messages](https://github.com/wpshadow/towerDefence/issues/11)
- [ ] [wpGUI Loader](https://github.com/wpshadow/towerDefence/issues/12)
- [x] wpGUI Button aktiviert/deaktiviert
- [x] wpGUI Background aktiviert/deaktiviert
- [x] wpGUI Radio Button aktiviert/deaktiviert
- [x] wpGUI Label aktiviert/deaktiviert

**Comment by wpshadow** [comment]
Dokumentation:

https://github.com/wpshadow/towerDefence/wiki/wpGUI_button
